export {
  ESPERA_REENVIO_SEGUNDOS,
  MAX_ENVIOS_POR_IP_24H,
  MAX_ENVIOS_POR_NUMERO_24H,
  MAX_TENTATIVAS,
  TAMANHO_CODIGO,
  VALIDADE_CODIGO_MINUTOS,
  avaliarConferencia,
  avaliarReenvio,
  avaliarTetoDeEnvio,
  expiracaoDe,
  gerarCodigo,
  tentativasRestantes,
  type DecisaoDeConferencia,
  type DecisaoDeReenvio,
  type DecisaoDeTeto,
  type EstadoDoDesafio,
  type Sorteio,
} from './codigo';
